name: tests
on: [push, workflow_dispatch]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart analyze --no-fatal-warnings
      - run: dart test
